### ISSUE TITLE
confirmation of the e-mail address in the new field is required

### ISSUE THREAD

**Issue by serhii73** [daniel-cortez-stevenson/anmeldung-berlin#7]
![Screenshot by Dropbox Capture](https://github.com/daniel-cortez-stevenson/anmeldung-berlin/assets/24910277/a8e6042a-396b-4ca3-b2e1-c90fe57c7240)
I need to make an Abmeldung. 
Launching your project, but unfortunately, it didn't work. It looks like a new field was added with email address confirmation. 
```
          bookingPage.$eval(
            "input#email",
            (el, config) => (el.value = config.email),
            config
          ),
```
Looks like we need to add another line like this, just with the correct id.

**Comment by daniel-cortez-stevenson** [comment]
Fixed in  #6
